version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: xrpg_postgres
    restart: always
    environment:
      POSTGRES_DB: XRPG
      POSTGRES_USER: xrpg_user
      POSTGRES_PASSWORD: xrpg_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
